---
title: "promisedat"
author: "David Holstius"
date: "January 30, 2015"
output: html_document
---

```{r wd}
getwd() # if clicked "Knit HTML" then this is "data-raw" (why?)
```

```{r}
library(devtools)
inst("promisedat") # if not yet installed then this is NULL
system.file(package = "promisedat") # if not yet installed then this is ""
```

## HACK so both "Run Chunk" and "Knit HTML" will work

```{r rel_path}
if (file.exists("data")) {
  pkg_root <- "." 
} else if (file.exists(file.path("..", "data"))) {
  pkg_root <- ".." # we're in data-raw/
} else {
  stop("We're lost")
}

rel_path <- function (...) {
  message("rel_path(): ", file.path(pkg_root))
  file.path(pkg_root, ...)
}

rel_path("data")
```

## To find `inst/` whether installed or not (yet) 

```{r inst_path}
# Prefer installed version but fall back to ./inst if not yet installed
inst_path <- function (...) {
  path <- system.file(package = "promisedat")
  message('inst_path(): `system.file(package = "promisedat")` is "', path, '"')
  if (nchar(path) == 0) {
     # why does this even happen?
    warning('`system.file(package = "promisedat")` yielded ""; using "." instead')
    path <- "."
  }
  if (!stringr::str_detect(path, stringr::ignore.case("inst$"))) {
    # happens during 1st load_all() but not the 2nd time
    warning('appending "inst"') 
    path <- file.path(path, "inst")
  }
  file.path(path, ...)
}

inst_path("extdata")
```

## The magic

```{r eval = TRUE}
# in real world, these are DB table names
datasets <- c(my_cars = "cars", my_iris = "iris")

my_env <- new.env()
assign("rel_path", rel_path, envir = my_env)
assign("inst_path", inst_path, envir = my_env)

for (.name in names(datasets)) {
  
  # in real world, we'd fetch a table here
  dat <- get(datasets[[.name]])                      
  
  # write to CSV file in pkg inst/extdata/
  csv_file <- force(paste0(.name, ".csv"))
  write.csv(dat, file = rel_path("inst", "extdata", csv_file))
  
  # create promise to read it
  promise_env <- new.env(parent = my_env)               
  assign("csv_file", csv_file, envir = promise_env)
  delayedAssign(
    .name, 
    {
      fn <- inst_path("extdata", csv_file)
      if (!file.exists(fn)) warning(fn, " doesn't exist") else read.csv(fn)
    },
    assign.env = my_env, 
    eval.env = promise_env)

}

save(
  list = names(datasets), 
  envir = my_env,
  file = rel_path("data", "promisedat.rda"), 
  eval.promises = FALSE)
```

## `load_all()` isn't idempotent

```{r}
load_all(rel_path())
load_all(rel_path())
```
